my_string=input('Текст: ')
print('Количество символов в тексте:',len(my_string))
print(my_string.upper())
print(my_string.upper().lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])